; Form Designer for PureBasic - 6.20
; Warning: this file uses a strict syntax, if you edit it, make sure to respect the Form Designer limitation or it won't be opened again.

;
; This code is automatically generated by the Form Designer.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures need to be put in another source file.
;

Global Window_0
Global form_title$
Global Text_0, Button_0, Button_1, Button_2, Button_3

Enumeration FormFont
  #Font_Window_0_0
  #Font_Window_0_1
  #Font_Window_0_2
EndEnumeration

LoadFont(#Font_Window_0_0,"標楷體", 16)
LoadFont(#Font_Window_0_1,"標楷體", 22)
LoadFont(#Font_Window_0_2,"標楷體", 26)

Declare Show_Second_Page(EventType)
Declare OK_Goto_Next(EventType)
Declare Maybe_Exit(EventType)
Declare Show_First_Page(EventType)

Procedure OpenWindow_0(x = 0, y = 0, width = 640, height = 400)
  form_title$ = "六大證型"
  Window_0 = OpenWindow(#PB_Any, x, y, width, height, form_title$, #PB_Window_SystemMenu)
  Text_0 = TextGadget(#PB_Any, 20, 30, 560, 30, "缺血性中風之人工智慧證型判斷與處置程式 (May, 2025)", #PB_Text_Center)
  SetGadgetColor(Text_0, #PB_Gadget_FrontColor,RGB(255,64,255))
  SetGadgetColor(Text_0, #PB_Gadget_BackColor,RGB(0,0,64))
  SetGadgetFont(Text_0, FontID(#Font_Window_0_0))
  Button_0 = ButtonGadget(#PB_Any, 40, 80, 230, 60, "顯示證型前頁")
  SetGadgetFont(Button_0, FontID(#Font_Window_0_1))
  Button_1 = ButtonGadget(#PB_Any, 370, 80, 230, 60, "顯示證型後頁")
  SetGadgetFont(Button_1, FontID(#Font_Window_0_1))
  Button_2 = ButtonGadget(#PB_Any, 20, 180, 590, 80, "我選好證型了請帶我進到下一步驟 (類神經網路運算)")
  SetGadgetFont(Button_2, FontID(#Font_Window_0_0))
  Button_3 = ButtonGadget(#PB_Any, 200, 300, 230, 80, "結束程式")
  SetGadgetFont(Button_3, FontID(#Font_Window_0_2))
EndProcedure

Procedure Window_0_Events(event)
  Select event
    Case #PB_Event_CloseWindow
      ProcedureReturn #False

    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect

    Case #PB_Event_Gadget
      Select EventGadget()
        Case Button_0
          Show_First_Page(EventType())          
        Case Button_1
          Show_Second_Page(EventType())          
        Case Button_2
          OK_Goto_Next(EventType())          
        Case Button_3
          Maybe_Exit(EventType())          
      EndSelect
  EndSelect
  ProcedureReturn #True
EndProcedure


; IDE Options = PureBasic 6.20 (Windows - x86)
; CursorPosition = 29
; FirstLine = 12
; Folding = -
; EnableXP
; DPIAware